### ISSUE TITLE
Enable a way to switch crypto on

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/docker-plugin#10]
Will just write it down here for now.

**Comment by squaremo** [comment]
In general I should be passing environment values along to weave launch. Possibly this will be obviated if I take weave launch out of the plugin's remit; i.e., let the user start both weave and the plugin themselves.

**Comment by squaremo** [comment]
I've put the launching of the router (in #13) in the script rather than in the plugin code. The script passes environment variables including `WEAVE_PASSWORD` and can be given `WEAVE_ARGS` to append to the launch command line. Alternatively, you can just treat the script as an example and start weave and the plugin with your own scripts.
